"use client";

import { useEffect, useMemo, useState } from "react";

type Week = { week: number; dates: string; mode?: string; unit: string; title: string; summary: string; outcomes: string[]; topics: string[]; example: string; quiz: { q: string; options: string[]; answer: number } };

const weeks: Week[] = [
  [1,"12–18 jul","Virtual","Fundamentos","Bienvenida al mundo de los compiladores","Descubre el proyecto incremental y las fases que convierten una idea en un programa ejecutable.",["Reconocer las fases principales","Definir el alcance del proyecto"],["¿Qué es un compilador?","Pipeline de traducción","CompilaMini"],"fuente → lexer → parser → AST → IR → destino","Un compilador transforma…",["código fuente en otro lenguaje","datos en imágenes","redes en grafos"],0],
  [2,"19–25 jul","Presencial","Fundamentos","Procesadores de lenguaje","Compara compiladores, intérpretes y máquinas virtuales; prepara Flex y Bison.",["Identificar fases de compilación","Distinguir compilador e intérprete"],["Preprocesador","Compilador","Ensamblador y enlazador"],"hola.cm → tokens → AST → código","¿Qué ejecuta el programa instrucción por instrucción?",["Intérprete","Lexer","Enlazador"],0],
  [3,"26 jul–1 ago","","Análisis léxico","Tokens, lexemas y patrones","Construye un escáner que clasifica cada fragmento significativo de la entrada.",["Reconocer tokens y lexemas","Explicar el buffering"],["Rol del lexer","Input buffering","Flex"],"let total = 42;  →  KW ID ASSIGN NUM SEMI","El lexema es…",["la categoría del token","el texto reconocido","el estado inicial"],1],
  [4,"2–8 ago","","Análisis léxico","Expresiones regulares y AFN","Modela patrones léxicos y observa cómo un AFN explora alternativas.",["Aplicar expresiones regulares","Comprender transiciones ε"],["Regex","AFN","Reglas en Flex"],"ID = [a-zA-Z_][a-zA-Z0-9_]*","¿Qué símbolo representa cero o más repeticiones?",["+","*","?"],1],
  [5,"9–15 ago","","Análisis léxico","AFN, AFD y escáneres","Convierte decisiones no deterministas en estados deterministas para reconocer tokens.",["Comparar AFN y AFD","Probar entradas válidas e inválidas"],["Construcción por subconjuntos","Estados de aceptación","Relación regex-autómata"],"{q0,q1} —a→ {q1,q2}","Un AFD tiene por símbolo…",["una transición por estado","muchas pilas","reglas ambiguas"],0],
  [6,"16–22 ago","Presencial","Evaluación","Examen Parcial I","Consolida fundamentos, tokens, expresiones regulares y autómatas.",["Demostrar dominio del análisis léxico","Detectar áreas a reforzar"],["Repaso guiado","Evaluación","Retroalimentación"],"Reto: diseña tokens para un lenguaje de calculadora","El parcial I evalúa principalmente…",["generación de código","análisis léxico","recolección de basura"],1],
  [7,"23–29 ago","","Integración","Lexer y tabla de símbolos","Conecta Flex con Bison y registra identificadores, tipos y ubicaciones.",["Preparar el flujo de tokens","Construir una tabla de símbolos"],["Interfaz yylex","Atributos de token","Símbolos"],"x : entero @ global","La tabla de símbolos almacena…",["identificadores y atributos","píxeles","solo operadores"],0],
  [8,"30 ago–5 sep","","Análisis sintáctico","El rol del parser","Valida la estructura de los tokens y aplica recuperación de errores.",["Relacionar tokens y gramática","Explicar errores sintácticos"],["Parser","Gramáticas","Bison","Recuperación"],"expr: expr '+' term | term ;","El parser recibe…",["tokens","bytes de máquina","píxeles"],0],
  [9,"6–12 sep","","Gramáticas","Gramáticas libres de contexto","Deriva cadenas, dibuja árboles y detecta ambigüedades.",["Producir derivaciones","Reconocer ambigüedad"],["GLC","Derivación izquierda","Árbol sintáctico"],"E ⇒ E + T ⇒ T + T ⇒ id + id","Una gramática es ambigua si…",["genera dos árboles para una cadena","tiene terminales","usa ε"],0],
  [10,"13–19 sep","","Gramáticas","Diseño de gramáticas","Elimina recursividad izquierda, factoriza y declara precedencia en Bison.",["Reducir conflictos sintácticos","Aplicar asociatividad"],["Recursividad izquierda","Factorización","Precedencia"],"E → E+T | T  ⇒  E → T E'","La factorización izquierda ayuda cuando…",["hay prefijos comunes","faltan tokens","sobra memoria"],0],
  [11,"20–26 sep","","Semántica","Acciones semánticas y AST","Construye nodos del AST mientras el parser reduce producciones.",["Relacionar reglas y acciones","Construir nodos básicos"],["Valores semánticos","AST","Ámbitos y tipos"],"Binary(+, Identifier(x), Number(2))","El AST omite normalmente…",["detalles sintácticos innecesarios","operadores","identificadores"],0],
  [12,"27 sep–3 oct","Presencial","Evaluación","Examen Parcial II","Integra gramáticas, parser, acciones semánticas, AST y símbolos.",["Demostrar dominio sintáctico","Validar integración lexer-parser"],["Repaso","Evaluación","Corrección"],"Reto: del token al AST","Bison se usa principalmente para…",["análisis sintáctico","diseño gráfico","redes"],0],
  [13,"4–10 oct","","Parsing","Descenso recursivo y reducciones","Compara análisis de arriba hacia abajo y de abajo hacia arriba.",["Comparar estrategias","Resolver conflictos"],["LL","LR","Shift/Reduce","Descenso recursivo"],"parseExpr() → parseTerm() → parseFactor()","Una reducción reemplaza…",["un handle por su no terminal","un token por bytes","un AST por texto"],0],
  [14,"11–17 oct","","Parsing","Tablas, conflictos y AST","Interpreta tablas de análisis y fortalece el manejo de errores.",["Leer una tabla de parsing","Construir un AST robusto"],["ACTION/GOTO","Conflictos","Errores","AST"],"state 4 + '+' → shift 7","ACTION decide…",["shift/reduce/accept","colores","tipos de memoria"],0],
  [15,"18–24 oct","","Representación","Generación de código intermedio","Recorre el AST y tradúcelo a una representación independiente de la máquina.",["Relacionar AST e IR","Emitir instrucciones simples"],["Representaciones intermedias","Recorridos","Temporales"],"t1 = b * c\na = t1 + d","La IR facilita…",["optimización y portabilidad","tipografía","entrada de audio"],0],
  [16,"25–31 oct","","Representación","Código de tres direcciones","Genera TAC para expresiones, control de flujo, funciones y coerciones.",["Generar temporales y etiquetas","Traducir control de flujo"],["TAC","Memoria","Saltos","Funciones","Tipos"],"ifFalse t1 goto L2","Una instrucción TAC usa como máximo…",["tres direcciones","tres compiladores","tres gramáticas"],0],
  [17,"1–7 nov","","Ejecución","Entornos de tiempo de ejecución","Organiza memoria, ámbitos y recolección de basura usando información semántica.",["Explicar stack y heap","Validar ámbitos"],["Registros de activación","Heap","Garbage collector"],"call f → push frame → return → pop frame","Una variable local suele vivir en…",["el stack","el lexer","la regex"],0],
  [18,"8–14 nov","","Código destino","Generación de código y flujo","Forma bloques básicos y grafos de flujo; prueba el compilador de extremo a extremo.",["Identificar bloques básicos","Validar el pipeline"],["Código destino","Bloques básicos","CFG","Pruebas E2E"],"L1: LOAD R1, a\n    ADD R1, b","Un líder inicia…",["un bloque básico","una expresión regular","una tabla hash"],0],
  [19,"15–21 nov","","Optimización","Optimización y generación final","Optimiza bloques, selecciona instrucciones y presenta el flujo integrado.",["Aplicar optimización local","Explicar el flujo completo"],["Código muerto","Plegado constante","Reescritura de árboles"],"x = 2 * 3  ⇒  x = 6","El plegado constante ocurre…",["en compilación","solo en red","al dibujar el AST"],0],
  [20,"22–28 nov","Presencial","Evaluación","Examen final","Demuestra dominio del pipeline completo: de la fuente al código generado.",["Integrar todas las fases","Defender decisiones de diseño"],["Evaluación final","Demostración","Retroalimentación"],"fuente ✓ lexer ✓ parser ✓ AST ✓ IR ✓ salida","La entrada de la generación intermedia es…",["el AST","el teclado","el AFD siempre"],0],
  [21,"29 nov–5 dic","","Cierre","Exámenes de recuperación","Recupera aprendizajes pendientes y cierra el portafolio del compilador.",["Evidenciar competencias","Reflexionar sobre el proyecto"],["Recuperación","Portafolio","Cierre"],"Bitácora: decisiones, pruebas y próximos pasos","El portafolio debe evidenciar…",["proceso y resultados","solo la nota","solo capturas"],0],
].map((w) => ({week:w[0],dates:w[1],mode:w[2],unit:w[3],title:w[4],summary:w[5],outcomes:w[6],topics:w[7],example:w[8],quiz:{q:w[9],options:w[10],answer:w[11]}} as Week));

const labs = [
  {id:"tokens",n:"01",title:"Laboratorio de tokens",desc:"Convierte código fuente en una secuencia clasificada.",tag:"Lexer"},
  {id:"regex",n:"02",title:"Banco de expresiones regulares",desc:"Prueba patrones contra lexemas de ejemplo.",tag:"Regex"},
  {id:"automata",n:"03",title:"Simulador AFN / AFD",desc:"Recorre estados y comprueba cadenas binarias.",tag:"Autómatas"},
  {id:"grammar",n:"04",title:"Taller de gramáticas",desc:"Explora derivaciones para expresiones aritméticas.",tag:"GLC"},
  {id:"parser",n:"05",title:"Parser y AST",desc:"Transforma una expresión en un árbol navegable.",tag:"Sintaxis"},
  {id:"symbols",n:"06",title:"Tabla de símbolos",desc:"Detecta declaraciones, tipos, ámbitos y usos.",tag:"Semántica"},
  {id:"ir",n:"07",title:"Código intermedio",desc:"Genera código de tres direcciones desde expresiones.",tag:"IR"},
  {id:"pipeline",n:"08",title:"Pipeline completo",desc:"Observa todas las fases sobre el mismo programa.",tag:"Proyecto"},
];

type ReviewQuestion = { q:string; options:string[]; answer:number; why:string };
const reviewQuestions: ReviewQuestion[] = [
  {q:"¿Qué hace principalmente un compilador?",options:["Sirve únicamente para escribir código fuente.","Transforma código fuente a otra representación y reporta errores.","Ejecuta siempre el programa línea por línea sin traducirlo.","Solo cambia los colores del código en un editor."],answer:1,why:"Un compilador traduce un programa y también informa los errores que encuentra durante el proceso."},
  {q:"¿Cuál de los siguientes es un ejemplo de token?",options:["IDENTIFICADOR","El programa completo","Una carpeta del proyecto","El botón de ejecutar del IDE"],answer:0,why:"IDENTIFICADOR es una categoría de token. Nombres concretos como total o precio pertenecen a esa categoría."},
  {q:"En «let total = 10;», ¿cuál opción puede ser un lexema?",options:["total","IDENTIFICADOR","NUMERO","Declaración de variable"],answer:0,why:"Un lexema es el texto exacto encontrado en el programa; aquí «total» es el texto y IDENTIFICADOR es su categoría."},
  {q:"¿Qué fase detecta un carácter no reconocido como $?",options:["Análisis léxico","Análisis sintáctico","Análisis semántico","Generación de código"],answer:0,why:"El lexer intenta formar tokens. Si ningún patrón reconoce $, produce un error léxico."},
  {q:"¿Qué fase detecta paréntesis desbalanceados?",options:["Análisis léxico","Análisis sintáctico","Optimización de código","Enlazado"],answer:1,why:"Los paréntesis sí son tokens válidos, pero su organización incumple la gramática; por eso es un error sintáctico."},
  {q:"¿Qué fase detecta una variable no declarada?",options:["Análisis léxico","Análisis sintáctico","Análisis semántico","Preprocesamiento"],answer:2,why:"La frase puede estar bien escrita, pero usar un nombre inexistente rompe el significado del programa."},
  {q:"¿Para qué sirve una expresión regular en compiladores?",options:["Para definir patrones de tokens.","Para ejecutar directamente el programa.","Para instalar el compilador.","Para crear ventanas gráficas."],answer:0,why:"Las expresiones regulares describen la forma de identificadores, números, palabras reservadas y otros tokens."},
  {q:"Flex y Bison tienen exactamente la misma función.",options:["Verdadero","Falso"],answer:1,why:"Flex genera el analizador léxico; Bison genera el analizador sintáctico. Trabajan juntos, pero no hacen lo mismo."},
  {q:"¿Qué herramienta se asocia más con análisis léxico?",options:["Flex","Bison","GitHub","PowerPoint"],answer:0,why:"Flex reconoce patrones de texto y produce tokens para el parser."},
  {q:"¿Qué herramienta se asocia más con análisis sintáctico?",options:["Flex","Bison","GitHub","PowerPoint"],answer:1,why:"Bison usa reglas gramaticales para comprobar la estructura de la secuencia de tokens."},
];

const simpleConcepts = [
  {icon:"Aa",title:"Lexema",simple:"La palabra exacta que aparece en el código.",example:"En «let total = 10», total es un lexema."},
  {icon:"ID",title:"Token",simple:"La etiqueta que explica qué clase de pieza es.",example:"total recibe la etiqueta IDENTIFICADOR."},
  {icon:"{}",title:"Sintaxis",simple:"Las reglas que indican cómo ordenar las piezas.",example:"(2 + 3 es inválido porque falta cerrar )."},
  {icon:"✓",title:"Semántica",simple:"Comprueba que el programa tenga sentido.",example:"total + precio falla si precio no fue declarado."},
];

const tokenize = (src:string) => src.match(/\b(?:let|if|else|while|return|int|float)\b|\d+(?:\.\d+)?|[A-Za-z_]\w*|==|!=|<=|>=|[+*/=;(){}<>-]/g)?.map((v) => ({v,t:/^(let|if|else|while|return|int|float)$/.test(v)?"KEYWORD":/^\d/.test(v)?"NUMBER":/^[A-Za-z_]/.test(v)?"IDENTIFIER":/^[;(){}]$/.test(v)?"DELIMITER":"OPERATOR"})) ?? [];

function LabWorkbench({labId}:{labId:string}) {
  const [source,setSource]=useState("let total = precio * 3 + 5;");
  const [regex,setRegex]=useState("^[a-zA-Z_][a-zA-Z0-9_]*$");
  const [sample,setSample]=useState("contador_2");
  const [binary,setBinary]=useState("1010");
  const tokens=tokenize(source);
  const regexOk=useMemo(()=>{try{return new RegExp(regex).test(sample)}catch{return false}},[regex,sample]);
  const evenOnes=binary.split("").filter(x=>x==="1").length%2===0;
  const ast = source.replace(/^(?:let\s+)?\w+\s*=\s*/,"").replace(/;$/,"").trim();
  const tac=(()=>{const m=ast.match(/(\w+|\d+)\s*([*\/])\s*(\w+|\d+)\s*([+-])\s*(\w+|\d+)/);return m?`t1 = ${m[1]} ${m[2]} ${m[3]}\nt2 = t1 ${m[4]} ${m[5]}\ntotal = t2`:`t1 = ${ast}\ntotal = t1`})();
  if(labId==="regex") return <Workbench title="Probador de expresiones regulares" hint="Edita el patrón o el lexema."><label>Patrón<input value={regex} onChange={e=>setRegex(e.target.value)}/></label><label>Lexema<input value={sample} onChange={e=>setSample(e.target.value)}/></label><div className={`verdict ${regexOk?"ok":"bad"}`}>{regexOk?"Coincide con el patrón":"No coincide"}</div></Workbench>;
  if(labId==="automata") return <Workbench title="AFD: paridad de unos" hint="El autómata acepta cadenas con cantidad par de 1."><label>Cadena binaria<input value={binary} onChange={e=>setBinary(e.target.value.replace(/[^01]/g,""))}/></label><div className="state-row"><span className="state active">q0</span>{binary.split("").map((c,i)=><span key={i} className="transition">—{c}→ <b>{binary.slice(0,i+1).split("").filter(x=>x==="1").length%2?"q1":"q0"}</b></span>)}</div><div className={`verdict ${evenOnes?"ok":"bad"}`}>{evenOnes?"Cadena aceptada":"Cadena rechazada"}</div></Workbench>;
  if(labId==="grammar") return <Workbench title="Derivación de una expresión" hint="Gramática: E → E + T | T; T → T * F | F; F → id | num"><div className="derivation"><b>E</b><span>⇒ E + T</span><span>⇒ T + T</span><span>⇒ F + T</span><span>⇒ id + T</span><span>⇒ id + F</span><span>⇒ id + num</span></div><div className="tree"><b>E</b><div><span>T → id</span><span>+</span><span>T → num</span></div></div></Workbench>;
  if(labId==="parser") return <Workbench title="Parser de expresiones y AST" hint="Prueba una asignación aritmética."><Editor source={source} setSource={setSource}/><div className="ast"><div className="ast-node root">Assign(total)</div><div className="branches"><div className="ast-node">Binary(+)</div></div><div className="leaves"><span>Binary(*)</span><span>Number(5)</span></div><div className="leaves"><span>precio</span><span>3</span></div></div></Workbench>;
  if(labId==="symbols") return <Workbench title="Inspector de tabla de símbolos" hint="Extrae identificadores del programa actual."><Editor source={source} setSource={setSource}/><table><thead><tr><th>Nombre</th><th>Categoría</th><th>Tipo</th><th>Ámbito</th></tr></thead><tbody>{[...new Set(tokens.filter(t=>t.t==="IDENTIFIER").map(t=>t.v))].map((id,i)=><tr key={id}><td>{id}</td><td>{i===0?"variable":"referencia"}</td><td>{/precio|total/.test(id)?"number":"inferido"}</td><td>global</td></tr>)}</tbody></table></Workbench>;
  if(labId==="ir") return <Workbench title="Generador de código de tres direcciones" hint="Los subárboles se convierten en temporales."><Editor source={source} setSource={setSource}/><pre className="output">{tac}</pre></Workbench>;
  if(labId==="pipeline") return <Workbench title="Pipeline completo" hint="Una misma entrada, seis representaciones."><Editor source={source} setSource={setSource}/><div className="pipeline">{[["1","Tokens",`${tokens.length} unidades`],["2","Parser","Asignación válida"],["3","AST",`Assign → ${ast}`],["4","Símbolos",`${new Set(tokens.filter(t=>t.t==="IDENTIFIER").map(t=>t.v)).size} identificadores`],["5","IR",tac.split("\n")[0]],["6","Destino","LOAD · MUL · ADD · STORE"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></Workbench>;
  return <Workbench title="Tokenizador interactivo" hint="Escribe código CompilaMini y observa la clasificación léxica."><Editor source={source} setSource={setSource}/><div className="tokens">{tokens.map((t,i)=><div key={i}><code>{t.v}</code><span>{t.t}</span></div>)}</div></Workbench>;
}

function Editor({source,setSource}:{source:string,setSource:(s:string)=>void}){return <label>Código fuente<textarea value={source} onChange={e=>setSource(e.target.value)} spellCheck={false}/></label>}
function Workbench({title,hint,children}:{title:string,hint:string,children:React.ReactNode}){return <div className="workbench"><div className="wb-head"><div><span>ENTORNO INTERACTIVO</span><h3>{title}</h3></div><span className="live">● EN VIVO</span></div><p>{hint}</p>{children}</div>}

function explainSimply(week:number){
  if(week<=2)return {idea:"Un compilador es un traductor: recibe un programa escrito por una persona y produce otra representación que la computadora puede procesar.",analogy:"Como traducir una receta del español a instrucciones precisas para una máquina de cocina."};
  if(week<=7)return {idea:"El análisis léxico corta el código en piezas pequeñas y les pone una etiqueta: palabra reservada, nombre, número u operador.",analogy:"Como separar una oración en palabras y decir si cada una es verbo, nombre o número."};
  if(week<=14)return {idea:"El análisis sintáctico comprueba si las piezas están en un orden permitido y construye un árbol que muestra su estructura.",analogy:"Las palabras pueden existir, pero «come Ana pan» no sigue el orden esperado; el parser revisa ese orden."};
  if(week<=16)return {idea:"El AST conserva lo importante del programa. Después se convierte en instrucciones simples usando temporales y etiquetas.",analogy:"Es como convertir una receta extensa en pasos breves: mezclar, calentar y servir."};
  if(week<=19)return {idea:"Las últimas fases organizan memoria, mejoran instrucciones y producen el código que ejecutará la máquina destino.",analogy:"Es revisar la ruta antes de viajar: eliminar vueltas innecesarias y elegir el camino más eficiente."};
  return {idea:"La evaluación conecta todas las fases: código, tokens, gramática, significado, representación intermedia y salida.",analogy:"Piensa siempre en la cadena completa: cada fase recibe el resultado de la anterior."};
}

export default function Home(){
  const [view,setView]=useState<"inicio"|"curso"|"labs"|"repaso">("inicio");
  const [selectedWeek,setSelectedWeek]=useState(0);
  const [selectedLab,setSelectedLab]=useState("tokens");
  const [completed,setCompleted]=useState<number[]>([]);
  const [quizResult,setQuizResult]=useState<null|boolean>(null);
  const [reviewAnswers,setReviewAnswers]=useState<Record<number,number>>({});
  const [reviewFinished,setReviewFinished]=useState(false);
  // El progreso existe únicamente en el dispositivo del estudiante.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{try{setCompleted(JSON.parse(localStorage.getItem("compilalab-progress")||"[]"))}catch{}},[]);
  const toggleComplete=(n:number)=>{const next=completed.includes(n)?completed.filter(x=>x!==n):[...completed,n];setCompleted(next);localStorage.setItem("compilalab-progress",JSON.stringify(next))};
  const progress=Math.round(completed.length/21*100);
  const week=weeks[selectedWeek];
  const plain=explainSimply(week.week);
  return <div className="app-shell">
    <header><button className="brand" onClick={()=>setView("inicio")}><span>CL</span><div>CompilaLab<small>LABORATORIO DE COMPILADORES</small></div></button><nav>{[["inicio","Inicio"],["curso","Aprender"],["labs","Practicar"],["repaso","Repaso y examen"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id as typeof view)}>{label}</button>)}</nav><button className="progress-pill" onClick={()=>setView("curso")}><span>{progress}%</span><i><b style={{width:`${progress}%`}}/></i></button></header>
    {view==="inicio"&&<main>
      <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> COMPILADORES · SEGUNDO SEMESTRE 2026</div><h1>Del código fuente<br/>a la <em>máquina.</em></h1><p>Un laboratorio interactivo para comprender, construir y conectar cada fase de un compilador.</p><div className="hero-actions"><button className="primary" onClick={()=>setView("curso")}>Comenzar la ruta <span>→</span></button><button className="ghost" onClick={()=>setView("labs")}>Explorar laboratorios</button></div><div className="course-meta"><span><b>21</b> semanas</span><span><b>08</b> laboratorios</span><span><b>05</b> créditos</span></div></div><div className="compiler-card"><div className="window-bar"><i/><i/><i/><span>compilamini.cm</span></div><pre><span className="purple">func</span> calcular(precio, cantidad) {'{'}{"\n"}  <span className="purple">let</span> subtotal = precio * cantidad;{"\n"}  <span className="purple">let</span> impuesto = subtotal * <span className="orange">0.12</span>;{"\n"}  <span className="purple">return</span> subtotal + impuesto;{"\n"}{'}'}</pre><div className="compile-flow"><div><span>01</span><b>LEXER</b><small>17 tokens</small></div><i>→</i><div><span>02</span><b>PARSER</b><small>AST válido</small></div><i>→</i><div><span>03</span><b>CÓDIGO</b><small>6 instrucciones</small></div></div><div className="success">✓ Compilación exitosa <small>0 errores · 4 ms</small></div></div></section>
      <section className="simple-start"><div className="section-heading"><div><span>EMPIEZA AQUÍ</span><h2>Cuatro ideas, en palabras simples.</h2></div><p>No necesitas saber de compiladores para comenzar.</p></div><div className="concept-grid">{simpleConcepts.map(c=><article key={c.title}><span>{c.icon}</span><h3>{c.title}</h3><p>{c.simple}</p><small>{c.example}</small></article>)}</div><div className="remember"><b>La idea clave</b><span>Un compilador trabaja como un traductor con varios revisores: uno separa palabras, otro revisa la gramática, otro comprueba el significado y el último produce una nueva versión del programa.</span></div></section>
      <section className="path-preview"><div className="section-heading"><div><span>RUTA DE APRENDIZAJE</span><h2>Primero aprende, luego practica.</h2></div><p>Cada etapa incluye explicación, ejemplo y comprobación.</p></div><div className="phase-grid">{[["01","ANÁLISIS LÉXICO","Reconoce las piezas del código","Semanas 3—7"],["02","ANÁLISIS SINTÁCTICO","Comprueba el orden de las piezas","Semanas 8—14"],["03","GENERACIÓN","Traduce a instrucciones más simples","Semanas 15—19"]].map((x,i)=><button key={x[0]} onClick={()=>{setSelectedWeek(i?i===1?7:14:2);setView("curso")}}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><small>{x[3]} <b>↗</b></small></button>)}</div></section>
      <section className="lab-preview"><div><span className="eyebrow"><span/> APRENDER HACIENDO</span><h2>Experimenta.<br/>Rompe. Comprende.</h2><p>Cada laboratorio convierte la teoría en algo que puedes manipular y observar en tiempo real.</p><button className="primary" onClick={()=>setView("labs")}>Abrir laboratorios <span>→</span></button></div><LabWorkbench labId="tokens"/></section>
    </main>}
    {view==="curso"&&<main className="course-page"><aside><div className="aside-title"><span>PROGRAMA 2026</span><h2>21 semanas</h2></div><div className="week-list">{weeks.map((w,i)=><button key={w.week} className={selectedWeek===i?"active":""} onClick={()=>{setSelectedWeek(i);setQuizResult(null)}}><span className={completed.includes(w.week)?"done":""}>{completed.includes(w.week)?"✓":String(w.week).padStart(2,"0")}</span><div><small>{w.unit}</small><b>{w.title}</b></div></button>)}</div></aside><article className="lesson"><div className="lesson-top"><div><span>SEMANA {String(week.week).padStart(2,"0")} · {week.dates.toUpperCase()} {week.mode&&`· ${week.mode.toUpperCase()}`}</span><h1>{week.title}</h1><p>{week.summary}</p></div><button className={completed.includes(week.week)?"completed":""} onClick={()=>toggleComplete(week.week)}>{completed.includes(week.week)?"✓ Completada":"Marcar completada"}</button></div><section className="plain-language"><span>EN PALABRAS SIMPLES</span><h2>{plain.idea}</h2><p><b>Una comparación útil:</b> {plain.analogy}</p></section><div className="lesson-grid"><section><span className="kicker">AHORA SÍ, LA LECCIÓN</span><h2>{week.unit}: conceptos esenciales</h2><p>Primero identifica qué recibe esta fase, qué trabajo realiza y qué entrega a la siguiente. Esa secuencia es más importante que memorizar palabras aisladas.</p><h3>Temas de la semana</h3><ul>{week.topics.map(t=><li key={t}>{t}</li>)}</ul></section><section className="outcomes"><span className="kicker">AL FINAL PODRÁS</span>{week.outcomes.map((o,i)=><div key={o}><b>0{i+1}</b><span>{o}</span></div>)}</section></div><section className="example"><div><span className="kicker">EJEMPLO GUIADO</span><h3>La idea en código</h3></div><pre>{week.example}</pre></section><section className="quiz"><span className="kicker">COMPRUEBA TU APRENDIZAJE</span><h3>{week.quiz.q}</h3><div>{week.quiz.options.map((o,i)=><button key={o} onClick={()=>setQuizResult(i===week.quiz.answer)}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{quizResult!==null&&<p className={quizResult?"good":"retry"}>{quizResult?"✓ Correcto. Puedes continuar.":"Aún no. Revisa la explicación sencilla e inténtalo otra vez."}</p>}</section><div className="lesson-nav"><button disabled={selectedWeek===0} onClick={()=>{setSelectedWeek(x=>x-1);setQuizResult(null)}}>← Semana anterior</button><button disabled={selectedWeek===20} onClick={()=>{setSelectedWeek(x=>x+1);setQuizResult(null)}}>Siguiente semana →</button></div></article></main>}
    {view==="labs"&&<main className="labs-page"><div className="labs-title"><span>LABORATORIOS INTERACTIVOS</span><h1>El compilador bajo el microscopio.</h1><p>Modifica la entrada y observa cómo cambia cada representación.</p></div><div className="labs-layout"><aside>{labs.map(l=><button key={l.id} className={selectedLab===l.id?"active":""} onClick={()=>setSelectedLab(l.id)}><span>{l.n}</span><div><small>{l.tag}</small><b>{l.title}</b><p>{l.desc}</p></div></button>)}</aside><LabWorkbench labId={selectedLab}/></div></main>}
    {view==="repaso"&&<main className="review-page"><div className="review-hero"><div><span>REPASO DE FUNDAMENTOS</span><h1>Comprueba lo aprendido.</h1><p>Estas preguntas provienen del material que compartiste. Puedes responder sin presión: al terminar verás la solución explicada, no solo una nota.</p></div><div className="score-card"><b>{reviewFinished?reviewQuestions.filter((q,i)=>reviewAnswers[i]===q.answer).length:Object.keys(reviewAnswers).length}</b><span>{reviewFinished?"respuestas correctas":"de 10 respondidas"}</span></div></div><div className="review-guide"><b>Antes de empezar</b><span>Recuerda: <strong>léxico = piezas</strong>, <strong>sintáctico = orden</strong>, <strong>semántico = significado</strong>.</span></div><section className="question-list">{reviewQuestions.map((q,qi)=><article key={q.q} className={reviewFinished?(reviewAnswers[qi]===q.answer?"correct":"incorrect"):""}><header><span>Pregunta {qi+1} de 10</span><b>1 punto</b></header><h2>{q.q}</h2><div>{q.options.map((o,oi)=><label key={o} className={reviewAnswers[qi]===oi?"selected":""}><input type="radio" name={`q-${qi}`} checked={reviewAnswers[qi]===oi} onChange={()=>{setReviewAnswers(a=>({...a,[qi]:oi}));setReviewFinished(false)}}/><span>{String.fromCharCode(65+oi)}</span>{o}</label>)}</div>{reviewFinished&&<p className="answer-explanation"><b>{reviewAnswers[qi]===q.answer?"✓ Correcto":"Respuesta correcta: "+q.options[q.answer]}</b>{q.why}</p>}</article>)}</section><div className="review-submit"><button className="primary" disabled={Object.keys(reviewAnswers).length<10} onClick={()=>setReviewFinished(true)}>Calificar mis respuestas <span>→</span></button>{Object.keys(reviewAnswers).length<10&&<small>Responde las {10-Object.keys(reviewAnswers).length} preguntas restantes.</small>}{reviewFinished&&<button className="ghost" onClick={()=>{setReviewAnswers({});setReviewFinished(false)}}>Intentar de nuevo</button>}</div></main>}
    <footer><div className="brand"><span>CL</span><div>CompilaLab<small>USPG · INGENIERÍA EN SISTEMAS</small></div></div><p>Construido a partir del sílabo de Compiladores 2026.</p><span>Luis Alberto Pérez Estrada · Sábados 13:45—16:45</span></footer>
  </div>
}
