"use client";

import { useEffect, useMemo, useState } from "react";

type Week = { week: number; dates: string; mode?: string; unit: string; title: string; summary: string; outcomes: string[]; topics: string[]; example: string; quiz: { q: string; options: string[]; answer: number } };

const weeks: Week[] = [
  [1,"12–18 jul","Virtual","Fundamentos","La fábrica de software","Distingue las herramientas de desarrollo, recorre la maquinaria oculta de un compilador y conoce el proyecto MiniLang del semestre.",["Distinguir editor, IDE, intérprete y compilador","Explicar las cinco transformaciones principales","Clasificar errores léxicos, sintácticos y semánticos"],["Herramientas de desarrollo","Evolución de compiladores","Lexer, parser y semántica","IR, optimización y código final","Proyecto MiniLang"],"let x = 10; → tokens → AST → tabla de símbolos → IR → código final","¿Qué distingue principalmente a un compilador?",["Edita texto y ejecuta línea por línea","Traduce y genera una representación ejecutable independiente","Solo revisa colores y formato"],1],
  [2,"19–25 jul","Presencial","Fundamentos","Procesadores de lenguaje","Compara compiladores, intérpretes y máquinas virtuales; prepara Flex y Bison.",["Identificar fases de compilación","Distinguir compilador e intérprete"],["Preprocesador","Compilador","Ensamblador y enlazador"],"hola.cm → tokens → AST → código","¿Qué ejecuta el programa instrucción por instrucción?",["Intérprete","Lexer","Enlazador"],0],
  [3,"26 jul–1 ago","","Análisis léxico","Tokens, lexemas y patrones","Construye un escáner que clasifica cada fragmento significativo de la entrada.",["Reconocer tokens y lexemas","Explicar el buffering"],["Rol del lexer","Input buffering","Flex"],"let total = 42;  →  KW ID ASSIGN NUM SEMI","El lexema es…",["la categoría del token","el texto reconocido","el estado inicial"],1],
  [4,"2–8 ago","","Análisis léxico","Expresiones regulares y AFN","Modela patrones léxicos y observa cómo un AFN explora alternativas.",["Aplicar expresiones regulares","Comprender transiciones ε"],["Regex","AFN","Reglas en Flex"],"ID = [a-zA-Z_][a-zA-Z0-9_]*","¿Qué símbolo representa cero o más repeticiones?",["+","*","?"],1],
  [5,"9–15 ago","","Análisis léxico","AFN, AFD y escáneres","Convierte decisiones no deterministas en estados deterministas para reconocer tokens.",["Comparar AFN y AFD","Probar entradas válidas e inválidas"],["Construcción por subconjuntos","Estados de aceptación","Relación regex-autómata"],"{q0,q1} —a→ {q1,q2}","Un AFD tiene por símbolo…",["una transición por estado","muchas pilas","reglas ambiguas"],0],
  [6,"16–22 ago","Presencial","Evaluación","Examen Parcial I","Consolida fundamentos, tokens, expresiones regulares y autómatas.",["Demostrar dominio del análisis léxico","Detectar áreas a reforzar"],["Repaso guiado","Evaluación","Retroalimentación"],"Reto: diseña tokens para un lenguaje de calculadora","El parcial I evalúa principalmente…",["generación de código","análisis léxico","recolección de basura"],1],
  [7,"23–29 ago","","Integración","Lexer y tabla de símbolos","Conecta Flex con Bison y registra identificadores, tipos y ubicaciones.",["Preparar el flujo de tokens","Construir una tabla de símbolos"],["Interfaz yylex","Atributos de token","Símbolos"],"x : entero @ global","La tabla de símbolos almacena…",["identificadores y atributos","píxeles","solo operadores"],0],
  [8,"30 ago–5 sep","","Análisis sintáctico","El rol del parser","Valida la estructura de los tokens y aplica recuperación de errores.",["Relacionar tokens y gramática","Explicar errores sintácticos"],["Parser","Gramáticas","Bison","Recuperación"],"expr: expr '+' term | term ;","El parser recibe…",["tokens","bytes de máquina","píxeles"],0],
  [9,"6–12 sep","","Gramáticas","Gramáticas libres de contexto","Deriva cadenas, dibuja árboles y detecta ambigüedades.",["Producir derivaciones","Reconocer ambigüedad"],["GLC","Derivación izquierda","Árbol sintáctico"],"E ⇒ E + T ⇒ T + T ⇒ id + id","Una gramática es ambigua si…",["genera dos árboles para una cadena","tiene terminales","usa ε"],0],
  [10,"13–19 sep","","Gramáticas","Diseño de gramáticas","Elimina recursividad izquierda, factoriza y declara precedencia en Bison.",["Reducir conflictos sintácticos","Aplicar asociatividad"],["Recursividad izquierda","Factorización","Precedencia"],"E → E+T | T  ⇒  E → T E'","La factorización izquierda ayuda cuando…",["hay prefijos comunes","faltan tokens","sobra memoria"],0],
  [11,"20–26 sep","","Semántica","Acciones semánticas y AST","Construye nodos del AST mientras el parser reduce producciones.",["Relacionar reglas y acciones","Construir nodos básicos"],["Valores semánticos","AST","Ámbitos y tipos"],"Binary(+, Identifier(x), Number(2))","El AST omite normalmente…",["detalles sintácticos innecesarios","operadores","identificadores"],0],
  [12,"27 sep–3 oct","Presencial","Evaluación","Examen Parcial II","Integra gramáticas, parser, acciones semánticas, AST y símbolos.",["Demostrar dominio sintáctico","Validar integración lexer-parser"],["Repaso","Evaluación","Corrección"],"Reto: del token al AST","Bison se usa principalmente para…",["análisis sintáctico","diseño gráfico","redes"],0],
  [13,"4–10 oct","","Parsing","Descenso recursivo y reducciones","Compara análisis de arriba hacia abajo y de abajo hacia arriba.",["Comparar estrategias","Resolver conflictos"],["LL","LR","Shift/Reduce","Descenso recursivo"],"parseExpr() → parseTerm() → parseFactor()","Una reducción reemplaza…",["un handle por su no terminal","un token por bytes","un AST por texto"],0],
  [14,"11–17 oct","","Parsing","Tablas, conflictos y AST","Interpreta tablas de análisis y fortalece el manejo de errores.",["Leer una tabla de parsing","Construir un AST robusto"],["ACTION/GOTO","Conflictos","Errores","AST"],"state 4 + '+' → shift 7","ACTION decide…",["shift/reduce/accept","colores","tipos de memoria"],0],
  [15,"18–24 oct","","Representación","Generación de código intermedio","Recorre el AST y tradúcelo a una representación independiente de la máquina.",["Relacionar AST e IR","Emitir instrucciones simples"],["Representaciones intermedias","Recorridos","Temporales"],"t1 = b * c\na = t1 + d","La IR facilita…",["optimización y portabilidad","tipografía","entrada de audio"],0],
  [16,"25–31 oct","","Representación","Código de tres direcciones","Genera TAC para expresiones, control de flujo, funciones y coerciones.",["Generar temporales y etiquetas","Traducir control de flujo"],["TAC","Memoria","Saltos","Funciones","Tipos"],"ifFalse t1 goto L2","Una instrucción TAC usa como máximo…",["tres direcciones","tres compiladores","tres gramáticas"],0],
  [17,"1–7 nov","","Ejecución","Entornos de tiempo de ejecución","Organiza memoria, ámbitos y recolección de basura usando información semántica.",["Explicar stack y heap","Validar ámbitos"],["Registros de activación","Heap","Garbage collector"],"call f → push frame → return → pop frame","Una variable local suele vivir en…",["el stack","el lexer","la regex"],0],
  [18,"8–14 nov","","Código destino","Generación de código y flujo","Forma bloques básicos y grafos de flujo; prueba el compilador de extremo a extremo.",["Identificar bloques básicos","Validar el pipeline"],["Código destino","Bloques básicos","CFG","Pruebas E2E"],"L1: LOAD R1, a\n    ADD R1, b","Un líder inicia…",["un bloque básico","una expresión regular","una tabla hash"],0],
  [19,"15–21 nov","","Optimización","Optimización y generación final","Optimiza bloques, selecciona instrucciones y presenta el flujo integrado.",["Aplicar optimización local","Explicar el flujo completo"],["Código muerto","Plegado constante","Reescritura de árboles"],"x = 2 * 3  ⇒  x = 6","El plegado constante ocurre…",["en compilación","solo en red","al dibujar el AST"],0],
  [20,"22–28 nov","Presencial","Evaluación","Examen final","Demuestra dominio del pipeline completo: de la fuente al código generado.",["Integrar todas las fases","Defender decisiones de diseño"],["Evaluación final","Demostración","Retroalimentación"],"fuente ✓ lexer ✓ parser ✓ AST ✓ IR ✓ salida","La entrada de la generación intermedia es…",["el AST","el teclado","el AFD siempre"],0],
  [21,"29 nov–5 dic","","Cierre","Exámenes de recuperación","Recupera aprendizajes pendientes y cierra el portafolio del compilador.",["Evidenciar competencias","Reflexionar sobre el proyecto"],["Recuperación","Portafolio","Cierre"],"Bitácora: decisiones, pruebas y próximos pasos","El portafolio debe evidenciar…",["proceso y resultados","solo la nota","solo capturas"],0],
].map((w) => ({week:w[0],dates:w[1],mode:w[2],unit:w[3],title:w[4],summary:w[5],outcomes:w[6],topics:w[7],example:w[8],quiz:{q:w[9],options:w[10],answer:w[11]}} as Week));

const labs = [
  {id:"tokens",n:"01",title:"Laboratorio de tokens",desc:"Convierte código fuente en una secuencia clasificada.",tag:"Lexer"},
  {id:"regex",n:"02",title:"Banco de expresiones regulares",desc:"Prueba patrones contra lexemas de ejemplo.",tag:"Regex"},
  {id:"automata",n:"03",title:"Simulador AFN / AFD",desc:"Recorre estados y comprueba cadenas binarias.",tag:"Autómatas"},
  {id:"grammar",n:"04",title:"Taller de gramáticas",desc:"Explora derivaciones para expresiones aritméticas.",tag:"GLC"},
  {id:"parser",n:"05",title:"Parser y AST",desc:"Transforma una expresión en un árbol navegable.",tag:"Sintaxis"},
  {id:"symbols",n:"06",title:"Tabla de símbolos",desc:"Detecta declaraciones, tipos, ámbitos y usos.",tag:"Semántica"},
  {id:"ir",n:"07",title:"Código intermedio",desc:"Genera código de tres direcciones desde expresiones.",tag:"IR"},
  {id:"pipeline",n:"08",title:"Pipeline completo",desc:"Observa todas las fases sobre el mismo programa.",tag:"Proyecto"},
];

type ReviewQuestion = { q:string; options:string[]; answer:number; why:string };
const reviewQuestions: ReviewQuestion[] = [
  {q:"¿Qué hace principalmente un compilador?",options:["Sirve únicamente para escribir código fuente.","Transforma código fuente a otra representación y reporta errores.","Ejecuta siempre el programa línea por línea sin traducirlo.","Solo cambia los colores del código en un editor."],answer:1,why:"Un compilador traduce un programa y también informa los errores que encuentra durante el proceso."},
  {q:"¿Cuál de los siguientes es un ejemplo de token?",options:["IDENTIFICADOR","El programa completo","Una carpeta del proyecto","El botón de ejecutar del IDE"],answer:0,why:"IDENTIFICADOR es una categoría de token. Nombres concretos como total o precio pertenecen a esa categoría."},
  {q:"En «let total = 10;», ¿cuál opción puede ser un lexema?",options:["total","IDENTIFICADOR","NUMERO","Declaración de variable"],answer:0,why:"Un lexema es el texto exacto encontrado en el programa; aquí «total» es el texto y IDENTIFICADOR es su categoría."},
  {q:"¿Qué fase detecta un carácter no reconocido como $?",options:["Análisis léxico","Análisis sintáctico","Análisis semántico","Generación de código"],answer:0,why:"El lexer intenta formar tokens. Si ningún patrón reconoce $, produce un error léxico."},
  {q:"¿Qué fase detecta paréntesis desbalanceados?",options:["Análisis léxico","Análisis sintáctico","Optimización de código","Enlazado"],answer:1,why:"Los paréntesis sí son tokens válidos, pero su organización incumple la gramática; por eso es un error sintáctico."},
  {q:"¿Qué fase detecta una variable no declarada?",options:["Análisis léxico","Análisis sintáctico","Análisis semántico","Preprocesamiento"],answer:2,why:"La frase puede estar bien escrita, pero usar un nombre inexistente rompe el significado del programa."},
  {q:"¿Para qué sirve una expresión regular en compiladores?",options:["Para definir patrones de tokens.","Para ejecutar directamente el programa.","Para instalar el compilador.","Para crear ventanas gráficas."],answer:0,why:"Las expresiones regulares describen la forma de identificadores, números, palabras reservadas y otros tokens."},
  {q:"Flex y Bison tienen exactamente la misma función.",options:["Verdadero","Falso"],answer:1,why:"Flex genera el analizador léxico; Bison genera el analizador sintáctico. Trabajan juntos, pero no hacen lo mismo."},
  {q:"¿Qué herramienta se asocia más con análisis léxico?",options:["Flex","Bison","GitHub","PowerPoint"],answer:0,why:"Flex reconoce patrones de texto y produce tokens para el parser."},
  {q:"¿Qué herramienta se asocia más con análisis sintáctico?",options:["Flex","Bison","GitHub","PowerPoint"],answer:1,why:"Bison usa reglas gramaticales para comprobar la estructura de la secuencia de tokens."},
];

const simpleConcepts = [
  {icon:"Aa",title:"Lexema",simple:"La palabra exacta que aparece en el código.",example:"En «let total = 10», total es un lexema."},
  {icon:"ID",title:"Token",simple:"La etiqueta que explica qué clase de pieza es.",example:"total recibe la etiqueta IDENTIFICADOR."},
  {icon:"{}",title:"Sintaxis",simple:"Las reglas que indican cómo ordenar las piezas.",example:"(2 + 3 es inválido porque falta cerrar )."},
  {icon:"✓",title:"Semántica",simple:"Comprueba que el programa tenga sentido.",example:"total + precio falla si precio no fue declarado."},
];

function WeekOneContent(){return <section className="week-one-content">
  <div className="week-one-intro"><span>CONTENIDO REAL DE CLASE</span><h2>Compilar no es solamente presionar “Ejecutar”.</h2><p>El botón visible es apenas la punta del iceberg. Debajo existe una cadena de transformaciones que lee el texto, comprueba su estructura y significado, lo optimiza y finalmente produce instrucciones para una máquina.</p></div>
  <div className="tool-comparison"><h3>1. No todas las herramientas hacen lo mismo</h3><div><article><b>Editor</b><small>Ejemplo: VS Code</small><p>Edita texto. No traduce ni ejecuta por sí solo.</p></article><article><b>IDE</b><small>Ejemplo: Visual Studio</small><p>Integra editor, depuración y herramientas externas.</p></article><article><b>Intérprete</b><small>Ejemplo: Python</small><p>Analiza y ejecuta el programa durante su uso.</p></article><article className="featured"><b>Compilador</b><small>Ejemplo: GCC / Clang</small><p>Analiza reglas profundas y genera otra representación ejecutable.</p></article></div></div>
  <div className="factory-rules"><h3>2. Reglas de nuestra fábrica de software</h3><div><article><b>Entregas técnicas</b><p>Repositorio, README, instrucciones claras de compilación y evidencia de pruebas.</p></article><article><b>Construcción incremental</b><p>No habrá una entrega mágica al final: lexer, parser y demás fases deben funcionar paso a paso.</p></article><article><b>Uso responsable de IA</b><p>La IA es copiloto para entender o depurar. No se debe entregar código que no puedas explicar y defender.</p></article></div></div>
  <div className="history-strip"><h3>3. La evolución respondió a cuellos de botella</h3><div><span><b>1950s · Fortran</b>Lenguajes de alto nivel evitan escribir directamente código de máquina.</span><i>→</i><span><b>1970s/80s · Lex y Yacc</b>Generadores automatizan analizadores a partir de patrones y gramáticas.</span><i>→</i><span><b>2000s · LLVM</b>Frontend, representación intermedia y backend permiten reutilizar componentes.</span></div><p>Hoy la IA también depende de compiladores: TensorFlow y PyTorch utilizan representaciones intermedias para ejecutar en CPU, GPU o TPU. JIT compila durante la ejecución para mejorar el rendimiento.</p></div>
  <div className="factory-pipeline"><h3>4. La cinta transportadora del código fuente</h3>{[["01","Análisis léxico","Lee y categoriza caracteres","Flex · regex · autómatas"],["02","Análisis sintáctico","Valida estructuras gramaticales","Bison · gramáticas · AST"],["03","Análisis semántico","Comprueba tipos, nombres y alcance","Tabla de símbolos"],["04","IR y optimización","Transforma a instrucciones independientes","Código de tres direcciones"],["05","Código final","Genera instrucciones para la máquina","Arquitectura destino"]].map(x=><article key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><span>{x[2]}</span><small>{x[3]}</small></div></article>)}</div>
  <div className="minilang-mission"><div><span>PROYECTO DEL SEMESTRE</span><h3>MiniLang, construido en tres etapas</h3><p>La meta es un lenguaje pequeño pero robusto. Es preferible un lenguaje funcional y bien probado que uno enorme que no compile.</p></div><ol><li><b>Lexer con Flex</b><span>Leer texto, descartar espacios e identificar palabras clave y números.</span></li><li><b>Parser con Bison</b><span>Crear la gramática y validar matemáticas, asignaciones e impresiones.</span></li><li><b>Intérprete y AST</b><span>Evaluar variables, manejar símbolos y ejecutar rutinas como print.</span></li></ol></div>
  <div className="error-diagnostic"><h3>5. Diagnóstico rápido: ¿dónde se rompe la fábrica?</h3><div><article><code>let total = 10$;</code><b>Error léxico</b><p>$ no pertenece al alfabeto o a las reglas del lenguaje.</p></article><article><code>let = total 10;</code><b>Error sintáctico</b><p>Las piezas existen, pero están en un orden gramatical inválido.</p></article><article><code>print saldo;</code><b>Error semántico</b><p>La estructura es válida, pero saldo no fue declarado.</p></article></div></div>
  <div className="reading-guide">
    <div className="reading-head"><div><span>ACTIVIDAD DE LECTURA · ENTREGA: 1 PÁGINA MÁXIMO</span><h3>Compilador e intérprete, explicado paso a paso</h3><p>Lee el artículo de IONOS y usa esta guía para comprenderlo antes de escribir tu opinión. La meta no es copiar definiciones, sino explicarlas con tus propias palabras.</p></div><a href="https://www.ionos.com/es-us/digitalguide/paginas-web/desarrollo-web/compilador-e-interprete/" target="_blank" rel="noreferrer">Leer artículo en IONOS ↗</a></div>
    <div className="reading-analogy"><b>La idea central</b><p>Imagina unas instrucciones escritas en un idioma que la computadora no comprende. El <strong>compilador</strong> traduce el documento completo antes de usarlo; el <strong>intérprete</strong> traduce y ejecuta cada instrucción mientras avanza. Los dos sirven de puente entre el lenguaje humano de programación y las instrucciones que entiende el procesador.</p></div>
    <div className="reading-compare"><article><span>ANTES DE EJECUTAR</span><h4>Compilador</h4><p>Traduce el programa completo y produce código listo para ejecutarse. La preparación inicial toma tiempo, pero el programa resultante suele ejecutarse con mayor rapidez.</p><small>Ejemplos típicos: C, C++ y Pascal.</small></article><article><span>DURANTE LA EJECUCIÓN</span><h4>Intérprete</h4><p>Lee, traduce y ejecuta el código paso a paso. Permite probar cambios rápidamente y localizar el punto donde aparece un error.</p><small>Ejemplos típicos: Python, Ruby y PHP.</small></article><article className="jit-card"><span>MODELO HÍBRIDO</span><h4>JIT · justo a tiempo</h4><p>Traduce a código máquina durante la ejecución y puede compilar las partes que se usan con frecuencia. Busca combinar facilidad de desarrollo con una ejecución más rápida.</p><small>Java es un ejemplo conocido de este enfoque.</small></article></div>
    <div className="question-workshop"><div className="question-title"><span>GUÍA PARA REDACTAR</span><h3>Responde las seis preguntas con tu criterio</h3><p>En cada respuesta incluye una idea del artículo y luego explica qué piensas tú. Estas pistas son puntos de partida, no respuestas para copiar.</p></div>{[
      ["01","¿Cuál es la diferencia principal?","Compara cuándo traducen: el compilador antes de ejecutar; el intérprete durante la ejecución, paso a paso.","Yo entiendo que la diferencia principal es…"],
      ["02","¿Por qué ambos son necesarios?","El procesador no ejecuta directamente los lenguajes de alto nivel; necesita una traducción a instrucciones legibles por la máquina.","Ambos son importantes porque una computadora…"],
      ["03","¿Qué ventaja tiene un lenguaje compilado?","Piensa en rendimiento, optimización y en disponer de un programa ya traducido.","Según mi criterio, su mayor ventaja es…"],
      ["04","¿Qué ventaja tiene un lenguaje interpretado?","Piensa en probar inmediatamente, modificar con rapidez y encontrar errores durante la ejecución.","Considero que resulta ventajoso cuando…"],
      ["05","¿Qué entendiste por compilación JIT?","Explica que compila durante la ejecución y que intenta reunir ventajas de compilación e interpretación.","Entendí JIT como un proceso que…"],
      ["06","¿Por qué importa en este curso?","Relaciona el tema con las fases, decisiones y herramientas que se estudiarán al construir MiniLang.","Este tema es importante en Compiladores porque…"]
    ].map(q=><article key={q[0]}><b>{q[0]}</b><div><h4>{q[1]}</h4><p>{q[2]}</p><small>{q[3]}</small></div></article>)}</div>
    <div className="writing-plan"><div><span>ESTRUCTURA SUGERIDA</span><h3>Cómo organizar una sola página</h3></div><ol><li><b>Introducción · 2–3 líneas</b><span>Presenta el propósito común del compilador y del intérprete.</span></li><li><b>Desarrollo · 3 párrafos breves</b><span>Compara ambos enfoques, sus ventajas y explica JIT.</span></li><li><b>Cierre · 3–4 líneas</b><span>Explica por qué el tema será útil en el curso y agrega tu opinión final.</span></li></ol><div className="delivery-check"><b>Antes de entregar</b><label><input type="checkbox"/> Respondí las seis preguntas.</label><label><input type="checkbox"/> Usé mis propias palabras y expresé mi opinión.</label><label><input type="checkbox"/> Revisé claridad, ortografía y extensión máxima.</label></div></div>
  </div>
</section>}

function analyzeLexical(src:string){
  const pattern=/\b(?:let|if|else|while|return|int|float)\b|\d+(?:\.\d+)?|[A-Za-z_]\w*|==|!=|<=|>=|[+*/=;(){}<>-]/g;
  const tokens:{v:string;t:string}[]=[];
  const errors:{text:string;position:number}[]=[];
  let last=0;
  for(const match of src.matchAll(pattern)){
    const start=match.index ?? 0;
    const gap=src.slice(last,start);
    for(let i=0;i<gap.length;i++)if(!/\s/.test(gap[i]))errors.push({text:gap[i],position:last+i+1});
    const v=match[0];
    tokens.push({v,t:/^(let|if|else|while|return|int|float)$/.test(v)?"KEYWORD":/^\d/.test(v)?"NUMBER":/^[A-Za-z_]/.test(v)?"IDENTIFIER":/^[;(){}]$/.test(v)?"DELIMITER":"OPERATOR"});
    last=start+v.length;
  }
  const tail=src.slice(last);
  for(let i=0;i<tail.length;i++)if(!/\s/.test(tail[i]))errors.push({text:tail[i],position:last+i+1});
  return {tokens,errors};
}
function LabWorkbench({labId}:{labId:string}) {
  const [source,setSource]=useState("let total = precio * 3 + 5;");
  const [regex,setRegex]=useState("^[a-zA-Z_][a-zA-Z0-9_]*$");
  const [sample,setSample]=useState("contador_2");
  const [binary,setBinary]=useState("1010");
  const [sentence,setSentence]=useState("id + num");
  const lexical=analyzeLexical(source);
  const tokens=lexical.tokens;
  const regexOk=useMemo(()=>{try{return new RegExp(regex).test(sample)}catch{return false}},[regex,sample]);
  const evenOnes=binary.split("").filter(x=>x==="1").length%2===0;
  const grammarOk=/^(id|num)(\s*[+*]\s*(id|num))*$/.test(sentence.trim());
  const parensBalanced=(source.match(/\(/g)?.length??0)===(source.match(/\)/g)?.length??0);
  const parserOk=lexical.errors.length===0&&parensBalanced&&/^(?:let|int|float)\s+[A-Za-z_]\w*\s*=\s*.+;$/.test(source.trim());
  const declarations=[...source.matchAll(/\b(?:let|int|float)\s+([A-Za-z_]\w*)/g)].map(m=>m[1]);
  const identifiers=[...new Set(tokens.filter(t=>t.t==="IDENTIFIER").map(t=>t.v))];
  const undeclared=identifiers.filter(id=>!declarations.includes(id));
  const ast = source.replace(/^(?:let\s+)?\w+\s*=\s*/,"").replace(/;$/,"").trim();
  const tac=(()=>{const m=ast.match(/(\w+|\d+)\s*([*\/])\s*(\w+|\d+)\s*([+-])\s*(\w+|\d+)/);return m?`t1 = ${m[1]} ${m[2]} ${m[3]}\nt2 = t1 ${m[4]} ${m[5]}\ntotal = t2`:`t1 = ${ast}\ntotal = t1`})();
  if(labId==="regex") return <Workbench title="Validador de expresiones regulares" hint="Comprueba si un lexema cumple el patrón que escribiste."><LabGuide validates="Sí valida si el texto completo coincide con la expresión regular." steps={["Modifica el patrón o el lexema.","El resultado cambia automáticamente.","Verde significa coincidencia; rojo significa que no cumple el patrón."]}/><div className="example-actions"><span>Prueba:</span><button onClick={()=>setSample("contador_2")}>Identificador válido</button><button onClick={()=>setSample("2contador")}>Identificador inválido</button></div><label>Patrón<input value={regex} onChange={e=>setRegex(e.target.value)}/></label><label>Lexema a comprobar<input value={sample} onChange={e=>setSample(e.target.value)}/></label><div className={`validation-result ${regexOk?"valid":"invalid"}`}><b>{regexOk?"✓ El lexema coincide":"✕ El lexema no coincide"}</b><span>{regexOk?`«${sample}» cumple el patrón.`:`«${sample}» no tiene la forma exigida por el patrón.`}</span></div><div className="scope-note"><b>Importante:</b> aquí se valida un patrón de texto, no un programa completo.</div></Workbench>;
  if(labId==="automata") return <Workbench title="Simulador AFD: paridad de unos" hint="Valida cadenas binarias con una cantidad par de dígitos 1."><LabGuide validates="Sí valida si la cadena pertenece al lenguaje del autómata." steps={["Escribe una cadena usando solamente 0 y 1.","Sigue los estados que recorre cada símbolo.","La cadena se acepta únicamente si termina en q0."]}/><div className="example-actions"><span>Prueba:</span><button onClick={()=>setBinary("1010")}>Aceptada: 1010</button><button onClick={()=>setBinary("1011")}>Rechazada: 1011</button></div><label>Cadena binaria<input value={binary} onChange={e=>setBinary(e.target.value.replace(/[^01]/g,""))}/></label><div className="state-row"><span className="state active">q0</span>{binary.split("").map((c,i)=><span key={i} className="transition">—{c}→ <b>{binary.slice(0,i+1).split("").filter(x=>x==="1").length%2?"q1":"q0"}</b></span>)}</div><div className={`validation-result ${evenOnes?"valid":"invalid"}`}><b>{evenOnes?"✓ Cadena aceptada":"✕ Cadena rechazada"}</b><span>{evenOnes?"Terminó en q0 porque tiene una cantidad par de unos.":"Terminó en q1 porque tiene una cantidad impar de unos."}</span></div></Workbench>;
  if(labId==="grammar") return <Workbench title="Validador de gramática aritmética" hint="Comprueba expresiones formadas por id, num, + y *."><LabGuide validates="Sí valida si la cadena puede producirse con la gramática mostrada." steps={["Escribe una expresión con id o num.","Sepárala usando + o *.","Comprueba si la gramática puede derivarla."]}/><div className="grammar-rule">E → E + T | T &nbsp; · &nbsp; T → T * F | F &nbsp; · &nbsp; F → id | num</div><div className="example-actions"><span>Prueba:</span><button onClick={()=>setSentence("id + num")}>Cadena válida</button><button onClick={()=>setSentence("+ id num")}>Cadena inválida</button></div><label>Cadena a validar<input value={sentence} onChange={e=>setSentence(e.target.value)}/></label><div className={`validation-result ${grammarOk?"valid":"invalid"}`}><b>{grammarOk?"✓ La gramática genera esta cadena":"✕ La gramática no genera esta cadena"}</b><span>{grammarOk?"La expresión alterna operandos y operadores correctamente.":"Se esperaba id o num, seguido opcionalmente por + o * y otro operando."}</span></div>{grammarOk&&<div className="derivation"><b>E</b><span>⇒ {sentence.trim()}</span></div>}</Workbench>;
  if(labId==="parser") return <Workbench title="Validador sintáctico y AST" hint="Comprueba la estructura de una declaración con asignación."><LabGuide validates="Sí valida una regla sencilla: tipo o let, identificador, =, expresión y punto y coma." steps={["Modifica el código de ejemplo.","Comprueba el resultado sintáctico.","Si es válido, observa su representación como árbol."]}/><div className="example-actions"><span>Prueba:</span><button onClick={()=>setSource("let total = precio * 3 + 5;")}>Sintaxis válida</button><button onClick={()=>setSource("let total precio * 3")}>Sintaxis inválida</button></div><Editor source={source} setSource={setSource}/><div className={`validation-result ${parserOk?"valid":"invalid"}`}><b>{parserOk?"✓ Sintaxis válida":"✕ Error sintáctico"}</b><span>{parserOk?"La declaración tiene las piezas en el orden esperado.":"Revisa que exista un nombre, el signo =, una expresión, paréntesis balanceados y ; al final."}</span></div>{parserOk&&<div className="ast"><div className="ast-node root">Assign</div><div className="branches"><div className="ast-node">Expresión: {ast}</div></div></div>}<div className="scope-note"><b>Importante:</b> una sintaxis válida todavía puede contener una variable no declarada; eso se revisa en <strong>Tabla de símbolos</strong>.</div></Workbench>;
  if(labId==="symbols") return <Workbench title="Validador semántico y tabla de símbolos" hint="Comprueba qué nombres fueron declarados antes de usarse."><LabGuide validates="Sí detecta identificadores usados sin una declaración let, int o float." steps={["Escribe una o varias declaraciones.","Observa la tabla de nombres encontrados.","El resultado rojo indica nombres usados pero no declarados."]}/><div className="example-actions"><span>Prueba:</span><button onClick={()=>setSource("let precio = 2; let total = precio * 3;")}>Nombres válidos</button><button onClick={()=>setSource("let total = precio * 3;")}>Falta declarar precio</button></div><Editor source={source} setSource={setSource}/><div className={`validation-result ${undeclared.length?"invalid":"valid"}`}><b>{undeclared.length?"✕ Variable no declarada":"✓ Uso de variables válido"}</b><span>{undeclared.length?`Debes declarar: ${undeclared.join(", ")}.`:"Todos los identificadores usados tienen una declaración."}</span></div><table><thead><tr><th>Nombre</th><th>Estado</th><th>Tipo</th><th>Ámbito</th></tr></thead><tbody>{identifiers.map(id=><tr key={id}><td>{id}</td><td>{declarations.includes(id)?"declarado":"no declarado"}</td><td>inferido</td><td>global</td></tr>)}</tbody></table></Workbench>;
  if(labId==="ir") return <Workbench title="Generador de código intermedio" hint="Convierte una asignación válida en instrucciones de tres direcciones."><LabGuide validates="Primero comprueba la sintaxis básica; luego genera temporales cuando la entrada es válida." steps={["Escribe una declaración con asignación.","Corrige cualquier error sintáctico.","Lee las instrucciones generadas línea por línea."]}/><Editor source={source} setSource={setSource}/><div className={`validation-result ${parserOk?"valid":"invalid"}`}><b>{parserOk?"✓ Código intermedio generado":"✕ No se puede generar código"}</b><span>{parserOk?"La expresión fue dividida en operaciones simples.":"Primero corrige la estructura de la declaración."}</span></div>{parserOk&&<pre className="output">{tac}</pre>}</Workbench>;
  if(labId==="pipeline") return <Workbench title="Validador del pipeline completo" hint="Muestra hasta dónde puede avanzar el mismo programa."><LabGuide validates="Revisa el análisis léxico y sintáctico antes de mostrar las fases posteriores." steps={["Modifica el programa.","Busca la primera fase roja.","Corrige esa fase para que el flujo pueda continuar."]}/><Editor source={source} setSource={setSource}/><div className={`validation-result ${lexical.errors.length||!parserOk?"invalid":"valid"}`}><b>{lexical.errors.length?"✕ El pipeline se detuvo en Lexer":!parserOk?"✕ El pipeline se detuvo en Parser":"✓ Pipeline completado"}</b><span>{lexical.errors.length?"Hay caracteres no reconocidos.":!parserOk?"Los tokens existen, pero la estructura no cumple la gramática.":"La entrada avanzó por todas las representaciones de demostración."}</span></div><div className="pipeline">{[["1","Tokens",lexical.errors.length?"ERROR":`${tokens.length} unidades`],["2","Parser",parserOk?"Asignación válida":"DETENIDO"],["3","AST",parserOk?`Assign → ${ast}`:"Sin generar"],["4","Símbolos",parserOk?`${identifiers.length} identificadores`:"Sin revisar"],["5","IR",parserOk?tac.split("\n")[0]:"Sin generar"],["6","Destino",parserOk?"LOAD · MUL · ADD · STORE":"Sin generar"]].map(x=><div key={x[0]} className={x[2]==="ERROR"||x[2]==="DETENIDO"?"stage-error":""}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></Workbench>;
  return <Workbench title="Validador léxico y tokenizador" hint="Aquí compruebas si cada carácter puede convertirse en un token válido."><div className="lab-instructions"><b>¿Qué debes hacer?</b><ol><li>Escribe o modifica el código.</li><li>El resultado se actualiza automáticamente; no necesitas pulsar un botón.</li><li>Revisa el mensaje verde o rojo y luego observa las etiquetas de cada pieza.</li></ol></div><div className="example-actions"><span>Prueba rápida:</span><button onClick={()=>setSource("let x = 1;")}>Ejemplo válido</button><button onClick={()=>setSource("let x = $;")}>Ejemplo con error</button></div><Editor source={source} setSource={setSource}/><div className={`validation-result ${lexical.errors.length?"invalid":"valid"}`}><b>{lexical.errors.length?"✕ Error léxico encontrado":"✓ Análisis léxico válido"}</b><span>{lexical.errors.length?`No se reconoce ${lexical.errors.map(e=>`«${e.text}» en la posición ${e.position}`).join(", ")}. Corrige ese carácter.`:`Todos los caracteres fueron reconocidos y se formaron ${tokens.length} tokens.`}</span></div><div className="scope-note"><b>Importante:</b> este laboratorio valida las piezas del código, no su orden. Para detectar paréntesis desbalanceados o una estructura incorrecta usa <strong>Parser y AST</strong>.</div><div className="tokens">{tokens.map((t,i)=><div key={i}><code>{t.v}</code><span>{t.t}</span></div>)}</div><div className="token-help"><span><b>KEYWORD</b> palabra reservada</span><span><b>IDENTIFIER</b> nombre creado por ti</span><span><b>NUMBER</b> número</span><span><b>OPERATOR</b> operación</span><span><b>DELIMITER</b> separador</span></div></Workbench>;
}

function Editor({source,setSource}:{source:string,setSource:(s:string)=>void}){return <label>Código fuente<textarea value={source} onChange={e=>setSource(e.target.value)} spellCheck={false}/></label>}
function LabGuide({validates,steps}:{validates:string,steps:string[]}){return <div className="lab-guide"><div><b>¿Qué valida?</b><span>{validates}</span></div><div><b>¿Qué debes hacer?</b><ol>{steps.map(s=><li key={s}>{s}</li>)}</ol></div></div>}
function Workbench({title,hint,children}:{title:string,hint:string,children:React.ReactNode}){return <div className="workbench"><div className="wb-head"><div><span>ENTORNO INTERACTIVO</span><h3>{title}</h3></div><span className="live">● EN VIVO</span></div><p>{hint}</p>{children}</div>}

function explainSimply(week:number){
  if(week<=2)return {idea:"Un compilador es un traductor: recibe un programa escrito por una persona y produce otra representación que la computadora puede procesar.",analogy:"Como traducir una receta del español a instrucciones precisas para una máquina de cocina."};
  if(week<=7)return {idea:"El análisis léxico corta el código en piezas pequeñas y les pone una etiqueta: palabra reservada, nombre, número u operador.",analogy:"Como separar una oración en palabras y decir si cada una es verbo, nombre o número."};
  if(week<=14)return {idea:"El análisis sintáctico comprueba si las piezas están en un orden permitido y construye un árbol que muestra su estructura.",analogy:"Las palabras pueden existir, pero «come Ana pan» no sigue el orden esperado; el parser revisa ese orden."};
  if(week<=16)return {idea:"El AST conserva lo importante del programa. Después se convierte en instrucciones simples usando temporales y etiquetas.",analogy:"Es como convertir una receta extensa en pasos breves: mezclar, calentar y servir."};
  if(week<=19)return {idea:"Las últimas fases organizan memoria, mejoran instrucciones y producen el código que ejecutará la máquina destino.",analogy:"Es revisar la ruta antes de viajar: eliminar vueltas innecesarias y elegir el camino más eficiente."};
  return {idea:"La evaluación conecta todas las fases: código, tokens, gramática, significado, representación intermedia y salida.",analogy:"Piensa siempre en la cadena completa: cada fase recibe el resultado de la anterior."};
}

export default function Home(){
  const [view,setView]=useState<"inicio"|"curso"|"labs"|"repaso">("inicio");
  const [selectedWeek,setSelectedWeek]=useState(0);
  const [selectedLab,setSelectedLab]=useState("tokens");
  const [completed,setCompleted]=useState<number[]>([]);
  const [quizResult,setQuizResult]=useState<null|boolean>(null);
  const [reviewAnswers,setReviewAnswers]=useState<Record<number,number>>({});
  const [reviewFinished,setReviewFinished]=useState(false);
  // El progreso existe únicamente en el dispositivo del estudiante.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{try{setCompleted(JSON.parse(localStorage.getItem("compilalab-progress")||"[]"))}catch{}},[]);
  const toggleComplete=(n:number)=>{const next=completed.includes(n)?completed.filter(x=>x!==n):[...completed,n];setCompleted(next);localStorage.setItem("compilalab-progress",JSON.stringify(next))};
  const progress=Math.round(completed.length/21*100);
  const week=weeks[selectedWeek];
  const plain=explainSimply(week.week);
  return <div className="app-shell">
    <header><button className="brand" onClick={()=>setView("inicio")}><span>CL</span><div>CompilaLab<small>LABORATORIO DE COMPILADORES</small></div></button><nav>{[["inicio","Inicio"],["curso","Aprender"],["labs","Practicar"],["repaso","Repaso y examen"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id as typeof view)}>{label}</button>)}</nav><button className="progress-pill" onClick={()=>setView("curso")}><span>{progress}%</span><i><b style={{width:`${progress}%`}}/></i></button></header>
    {view==="inicio"&&<main>
      <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> COMPILADORES · SEGUNDO SEMESTRE 2026</div><h1>Del código fuente<br/>a la <em>máquina.</em></h1><p>Un laboratorio interactivo para comprender, construir y conectar cada fase de un compilador.</p><div className="hero-actions"><button className="primary" onClick={()=>setView("curso")}>Comenzar la ruta <span>→</span></button><button className="ghost" onClick={()=>setView("labs")}>Explorar laboratorios</button></div><div className="course-meta"><span><b>21</b> semanas</span><span><b>08</b> laboratorios</span><span><b>05</b> créditos</span></div></div><div className="compiler-card"><div className="window-bar"><i/><i/><i/><span>compilamini.cm</span></div><pre><span className="purple">func</span> calcular(precio, cantidad) {'{'}{"\n"}  <span className="purple">let</span> subtotal = precio * cantidad;{"\n"}  <span className="purple">let</span> impuesto = subtotal * <span className="orange">0.12</span>;{"\n"}  <span className="purple">return</span> subtotal + impuesto;{"\n"}{'}'}</pre><div className="compile-flow"><div><span>01</span><b>LEXER</b><small>17 tokens</small></div><i>→</i><div><span>02</span><b>PARSER</b><small>AST válido</small></div><i>→</i><div><span>03</span><b>CÓDIGO</b><small>6 instrucciones</small></div></div><div className="success">✓ Compilación exitosa <small>0 errores · 4 ms</small></div></div></section>
      <section className="simple-start"><div className="section-heading"><div><span>EMPIEZA AQUÍ</span><h2>Cuatro ideas, en palabras simples.</h2></div><p>No necesitas saber de compiladores para comenzar.</p></div><div className="concept-grid">{simpleConcepts.map(c=><article key={c.title}><span>{c.icon}</span><h3>{c.title}</h3><p>{c.simple}</p><small>{c.example}</small></article>)}</div><div className="remember"><b>La idea clave</b><span>Un compilador trabaja como un traductor con varios revisores: uno separa palabras, otro revisa la gramática, otro comprueba el significado y el último produce una nueva versión del programa.</span></div></section>
      <section className="path-preview"><div className="section-heading"><div><span>RUTA DE APRENDIZAJE</span><h2>Primero aprende, luego practica.</h2></div><p>Cada etapa incluye explicación, ejemplo y comprobación.</p></div><div className="phase-grid">{[["01","ANÁLISIS LÉXICO","Reconoce las piezas del código","Semanas 3—7"],["02","ANÁLISIS SINTÁCTICO","Comprueba el orden de las piezas","Semanas 8—14"],["03","GENERACIÓN","Traduce a instrucciones más simples","Semanas 15—19"]].map((x,i)=><button key={x[0]} onClick={()=>{setSelectedWeek(i?i===1?7:14:2);setView("curso")}}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><small>{x[3]} <b>↗</b></small></button>)}</div></section>
      <section className="lab-preview"><div><span className="eyebrow"><span/> APRENDER HACIENDO</span><h2>Experimenta.<br/>Rompe. Comprende.</h2><p>Cada laboratorio convierte la teoría en algo que puedes manipular y observar en tiempo real.</p><button className="primary" onClick={()=>setView("labs")}>Abrir laboratorios <span>→</span></button></div><LabWorkbench labId="tokens"/></section>
    </main>}
    {view==="curso"&&<main className="course-page"><aside><div className="aside-title"><span>PROGRAMA 2026</span><h2>21 semanas</h2></div><div className="week-list">{weeks.map((w,i)=><button key={w.week} className={selectedWeek===i?"active":""} onClick={()=>{setSelectedWeek(i);setQuizResult(null)}}><span className={completed.includes(w.week)?"done":""}>{completed.includes(w.week)?"✓":String(w.week).padStart(2,"0")}</span><div><small>{w.unit}</small><b>{w.title}</b></div></button>)}</div></aside><article className="lesson"><div className="lesson-top"><div><span>SEMANA {String(week.week).padStart(2,"0")} · {week.dates.toUpperCase()} {week.mode&&`· ${week.mode.toUpperCase()}`}</span><h1>{week.title}</h1><p>{week.summary}</p></div><button className={completed.includes(week.week)?"completed":""} onClick={()=>toggleComplete(week.week)}>{completed.includes(week.week)?"✓ Completada":"Marcar completada"}</button></div><section className="plain-language"><span>EN PALABRAS SIMPLES</span><h2>{plain.idea}</h2><p><b>Una comparación útil:</b> {plain.analogy}</p></section>{week.week===1&&<WeekOneContent/>}<div className="lesson-grid"><section><span className="kicker">{week.week===1?"RESUMEN DE LA SEMANA":"AHORA SÍ, LA LECCIÓN"}</span><h2>{week.unit}: conceptos esenciales</h2><p>Primero identifica qué recibe esta fase, qué trabajo realiza y qué entrega a la siguiente. Esa secuencia es más importante que memorizar palabras aisladas.</p><h3>Temas de la semana</h3><ul>{week.topics.map(t=><li key={t}>{t}</li>)}</ul></section><section className="outcomes"><span className="kicker">AL FINAL PODRÁS</span>{week.outcomes.map((o,i)=><div key={o}><b>0{i+1}</b><span>{o}</span></div>)}</section></div><section className="example"><div><span className="kicker">EJEMPLO GUIADO</span><h3>La idea en código</h3></div><pre>{week.example}</pre></section><section className="quiz"><span className="kicker">COMPRUEBA TU APRENDIZAJE</span><h3>{week.quiz.q}</h3><div>{week.quiz.options.map((o,i)=><button key={o} onClick={()=>setQuizResult(i===week.quiz.answer)}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{quizResult!==null&&<p className={quizResult?"good":"retry"}>{quizResult?"✓ Correcto. Puedes continuar.":"Aún no. Revisa la explicación sencilla e inténtalo otra vez."}</p>}</section><div className="lesson-nav"><button disabled={selectedWeek===0} onClick={()=>{setSelectedWeek(x=>x-1);setQuizResult(null)}}>← Semana anterior</button><button disabled={selectedWeek===20} onClick={()=>{setSelectedWeek(x=>x+1);setQuizResult(null)}}>Siguiente semana →</button></div></article></main>}
    {view==="labs"&&<main className="labs-page"><div className="labs-title"><span>LABORATORIOS INTERACTIVOS</span><h1>El compilador bajo el microscopio.</h1><p>Modifica la entrada y observa cómo cambia cada representación.</p></div><div className="labs-layout"><aside>{labs.map(l=><button key={l.id} className={selectedLab===l.id?"active":""} onClick={()=>setSelectedLab(l.id)}><span>{l.n}</span><div><small>{l.tag}</small><b>{l.title}</b><p>{l.desc}</p></div></button>)}</aside><LabWorkbench labId={selectedLab}/></div></main>}
    {view==="repaso"&&<main className="review-page"><div className="review-hero"><div><span>REPASO DE FUNDAMENTOS</span><h1>Comprueba lo aprendido.</h1><p>Estas preguntas provienen del material que compartiste. Puedes responder sin presión: al terminar verás la solución explicada, no solo una nota.</p></div><div className="score-card"><b>{reviewFinished?reviewQuestions.filter((q,i)=>reviewAnswers[i]===q.answer).length:Object.keys(reviewAnswers).length}</b><span>{reviewFinished?"respuestas correctas":"de 10 respondidas"}</span></div></div><div className="review-guide"><b>Antes de empezar</b><span>Recuerda: <strong>léxico = piezas</strong>, <strong>sintáctico = orden</strong>, <strong>semántico = significado</strong>.</span></div><section className="question-list">{reviewQuestions.map((q,qi)=><article key={q.q} className={reviewFinished?(reviewAnswers[qi]===q.answer?"correct":"incorrect"):""}><header><span>Pregunta {qi+1} de 10</span><b>1 punto</b></header><h2>{q.q}</h2><div>{q.options.map((o,oi)=><label key={o} className={reviewAnswers[qi]===oi?"selected":""}><input type="radio" name={`q-${qi}`} checked={reviewAnswers[qi]===oi} onChange={()=>{setReviewAnswers(a=>({...a,[qi]:oi}));setReviewFinished(false)}}/><span>{String.fromCharCode(65+oi)}</span>{o}</label>)}</div>{reviewFinished&&<p className="answer-explanation"><b>{reviewAnswers[qi]===q.answer?"✓ Correcto":"Respuesta correcta: "+q.options[q.answer]}</b>{q.why}</p>}</article>)}</section><div className="review-submit"><button className="primary" disabled={Object.keys(reviewAnswers).length<10} onClick={()=>setReviewFinished(true)}>Calificar mis respuestas <span>→</span></button>{Object.keys(reviewAnswers).length<10&&<small>Responde las {10-Object.keys(reviewAnswers).length} preguntas restantes.</small>}{reviewFinished&&<button className="ghost" onClick={()=>{setReviewAnswers({});setReviewFinished(false)}}>Intentar de nuevo</button>}</div></main>}
    <footer><div className="brand"><span>CL</span><div>CompilaLab<small>USPG · INGENIERÍA EN SISTEMAS</small></div></div><p>Construido a partir del sílabo de Compiladores 2026.</p><span>Luis Alberto Pérez Estrada · Sábados 13:45—16:45</span></footer>
  </div>
}
